# Generated by Django 5.2.1 on 2025-06-13 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('contato', models.CharField(blank=True, max_length=20, verbose_name='Contato')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('nacionalidade', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(blank=True, max_length=50, verbose_name='Naturalidade')),
                ('estado_civil', models.CharField(blank=True, max_length=20, verbose_name='Estado Civil')),
                ('nome_pai', models.CharField(blank=True, max_length=100, verbose_name='Nome do Pai')),
                ('escolaridade_pai', models.CharField(blank=True, max_length=50, verbose_name='Escolaridade do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=100, verbose_name='Nome da Mãe')),
                ('escolaridade_mae', models.CharField(blank=True, max_length=50, verbose_name='Escolaridade da Mãe')),
                ('renda_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda familiar média')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('cursos_interesse', models.JSONField(blank=True, null=True, verbose_name='Cursos de Interesse')),
                ('periodos', models.JSONField(blank=True, null=True, verbose_name='Períodos')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='voluntario', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='voluntarios/perfis/fotos/', verbose_name='Foto Principal')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('data_nascimento_voluntario', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('descricao_atividades', models.TextField(blank=True, verbose_name='Descrição das Atividades/Interesses')),
            ],
        ),
    ]
