# Generated by Django 5.2.1 on 2025-06-14 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=100, verbose_name='Nome completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='numero',
            field=models.CharField(default=0, max_length=20, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='rua',
            field=models.CharField(default='Desconhecido', max_length=200, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='status_processo_voluntario',
            field=models.CharField(choices=[('AGUARDANDO_DOCUMENTOS', 'Aguardando Documentos'), ('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='AGUARDANDO_DOCUMENTOS', max_length=50, verbose_name='Status do Processo'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='tipo_voluntario',
            field=models.CharField(choices=[('APOIO_ADMINISTRATIVO', 'Apoio Administrativo'), ('PROFESSOR', 'Professor(a)'), ('MONITOR', 'Monitor(a)'), ('OUTRO', 'Outro / Não especificado')], default='OUTRO', max_length=50, verbose_name='Tipo de Voluntário'),
        ),
    ]
