# Generated by Django 5.2.1 on 2025-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="escolaridade_mae",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ensino_fundamental_incompleto", "Ensino Fundamental Incompleto"),
                    ("ensino_fundamental_completo", "Ensino Fundamental Completo"),
                    ("ensino_medio_incompleto", "Ensino Médio Incompleto"),
                    ("ensino_medio_completo", "Ensino Médio Completo"),
                    ("ensino_superior_incompleto", "Ensino Superior Incompleto"),
                    ("ensino_superior_completo", "Ensino Superior Completo"),
                ],
                max_length=50,
                verbose_name="Escolaridade da Mãe",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="escolaridade_pai",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ensino_fundamental_incompleto", "Ensino Fundamental Incompleto"),
                    ("ensino_fundamental_completo", "Ensino Fundamental Completo"),
                    ("ensino_medio_incompleto", "Ensino Médio Incompleto"),
                    ("ensino_medio_completo", "Ensino Médio Completo"),
                    ("ensino_superior_incompleto", "Ensino Superior Incompleto"),
                    ("ensino_superior_completo", "Ensino Superior Completo"),
                ],
                max_length=50,
                verbose_name="Escolaridade do Pai",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("solteiro", "Solteiro(a)"),
                    ("casado", "Casado(a)"),
                    ("divorciado", "Divorciado(a)"),
                    ("viuvo", "Viúvo(a)"),
                ],
                default="solteiro",
                max_length=20,
                verbose_name="Estado Civil",
            ),
        ),
    ]
