# Generated by Django 5.2.1 on 2025-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("id_turma", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Nome da Turma"
                    ),
                ),
                (
                    "capacidade",
                    models.IntegerField(
                        verbose_name="Capacidade de total de alunos na turma"
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("status", models.IntegerField(choices=[(0, "INATIVO"), (1, "ATIVO")])),
            ],
        ),
        migrations.RenameModel(
            old_name="Student",
            new_name="Aluno",
        ),
    ]
