# Generated by Django 5.2.1 on 2025-06-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voluntarios',
            new_name='Voluntario',
        ),
    ]
