# Generated by Django 5.2.1 on 2025-06-14 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_voluntario_bairro_voluntario_cep_voluntario_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='data_nascimento_voluntario',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_inicio_processo',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Data de Início do Processo'),
        ),
    ]
