# Generated by Django 5.2.1 on 2025-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_student_voluntario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
    ]
