# Generated by Django 5.2.3 on 2025-06-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_voluntario_data_nascimento_voluntario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo_Letivo',
            fields=[
                ('id_periodo_letivo', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(verbose_name='Ano do Período Letivo')),
                ('semestre', models.IntegerField(verbose_name='Semestre do Período Letivo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Período Letivo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Período Letivo')),
                ('data_fim', models.DateField(verbose_name='Data do Final do Período Letivo')),
                ('status', models.IntegerField(choices=[(0, 'INATIVO'), (1, 'ATIVO')], verbose_name='0 - Inativo; 1 - Ativo')),
            ],
        ),
    ]
