# Generated by Django 5.2.1 on 2025-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_voluntario_data_nascimento_voluntario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da disciplina. Exemplo: Matemática, Biologia, etc.', max_length=100, unique=True, verbose_name='Nome da Disciplina')),
                ('descricao', models.TextField(blank=True, help_text='Opcional: Adicione uma descrição detalhada da disciplina.', null=True, verbose_name='Descrição')),
                ('area_conhecimento', models.CharField(choices=[('CIENCIAS_NATUREZA', 'Ciências da Natureza'), ('CIENCIAS_HUMANAS', 'Ciências Humanas'), ('LINGUAGENS', 'Linguagens'), ('MATEMATICA', 'Matemática')], default='MATEMATICA', help_text='Selecione a área de conhecimento à qual esta disciplina pertence.', max_length=50, verbose_name='Área de Conhecimento')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
    ]
