# Generated by Django 5.2.1 on 2025-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='descricao',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curriculo',
            field=models.TextField(blank=True, help_text='Opcional: Adicione o currículo da disciplina.', null=True, verbose_name='Currículo'),
        ),
    ]
