# Generated by Django 5.2.3 on 2025-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_periodo_letivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo_letivo',
            name='status',
            field=models.IntegerField(choices=[(0, 'INATIVO'), (1, 'ATIVO')], verbose_name='Status'),
        ),
    ]
