# Generated by Django 5.2.1 on 2025-06-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='periodos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodo_interesse',
            field=models.IntegerField(choices=[(0, 'Matutino'), (1, 'Vespertino'), (2, 'Noturno')], default=0, verbose_name='Período de Interesse'),
        ),
    ]
