# Generated by Django 5.2.3 on 2025-06-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_periodo_letivo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo_letivo',
            options={'verbose_name': 'Período Letivo', 'verbose_name_plural': 'Períodos Letivos'},
        ),
    ]
