# Generated by Django 5.2.1 on 2025-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_aluno_periodos_aluno_periodo_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cursos_interesse',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos_interesse',
            field=models.ManyToManyField(blank=True, to='cadastros.curso', verbose_name='Cursos de Interesse'),
        ),
    ]
