# Generated by Django 5.2.1 on 2025-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_disciplina_descricao_disciplina_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, help_text='Opcional: Adicione uma descrição detalhada da disciplina.', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1, help_text='0 - Inativo (não disponível para matrícula); 1 - Ativo (disponível para matrícula).', verbose_name='Status da Disciplina'),
        ),
    ]
