# Generated by Django 5.2.1 on 2025-06-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_aluno_cursos_interesse_aluno_cursos_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cursos_interesse',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_interesse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.curso', verbose_name='Curso de Interesse'),
        ),
    ]
