# Generated by Django 5.2.1 on 2025-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_disciplina_descricao_disciplina_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1, verbose_name='Status da Disciplina'),
        ),
    ]
