# Generated by Django 5.2.1 on 2025-06-14 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0006_alter_periodo_letivo_options"),
        ("cadastros", "0007_remove_aluno_cursos_interesse_aluno_curso_interesse"),
        ("cadastros", "0007_remove_disciplina_descricao_alter_disciplina_status"),
    ]

    operations = []
