# Generated by Django 5.2.3 on 2025-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_merge_20250614_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo_letivo',
            name='data_fim',
            field=models.DateField(verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='periodo_letivo',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
    ]
