# Generated by Django 5.2.1 on 2025-06-14 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0008_merge_20250614_1438"),
        ("cadastros", "0008_merge_20250614_1446"),
    ]

    operations = []
