# Generated by Django 5.2.1 on 2025-06-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0009_merge_20250614_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="id_periodo_letivo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.periodo_letivo",
                verbose_name="Período Letivo",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="capacidade",
            field=models.IntegerField(
                verbose_name="Capacidade total de alunos na turma"
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="status",
            field=models.IntegerField(
                choices=[(0, "INATIVO"), (1, "ATIVO")], verbose_name="Status"
            ),
        ),
    ]
