# Generated by Django 5.2.1 on 2025-06-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0010_turma_id_periodo_letivo_alter_turma_capacidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurmaDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_disciplina",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "id_turma",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
        ),
    ]
