# Generated by Django 5.2.1 on 2025-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0011_turmadisciplina"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="turmadisciplina",
            options={
                "verbose_name": "Turma Disciplina",
                "verbose_name_plural": "Turmas & Disciplinas",
            },
        ),
        migrations.AddField(
            model_name="turmadisciplina",
            name="status",
            field=models.IntegerField(
                choices=[(0, "INATIVO"), (1, "ATIVO")],
                default=1,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
