# Generated by Django 5.2.1 on 2025-06-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0012_alter_turmadisciplina_options_turmadisciplina_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="turmadisciplina",
            options={
                "verbose_name": "Turma Disciplina",
                "verbose_name_plural": "Disciplinas das Turmas",
            },
        ),
        migrations.AlterUniqueTogether(
            name="turmadisciplina",
            unique_together={("id_turma", "id_disciplina")},
        ),
        migrations.CreateModel(
            name="AlunoTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "INATIVO"), (1, "ATIVO")],
                        default=1,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "id_aluno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "id_turma",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno Turma",
                "verbose_name_plural": "Alunos das Turmas",
                "unique_together": {("id_turma", "id_aluno")},
            },
        ),
    ]
