# Generated by Django 5.2.1 on 2025-06-14 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0013_alter_turmadisciplina_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AlunoTurma",
            new_name="TurmaAluno",
        ),
    ]
