# Generated by Django 5.2.1 on 2025-06-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0014_rename_alunoturma_turmaaluno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="turma",
            old_name="id_periodo_letivo",
            new_name="periodo_letivo",
        ),
        migrations.RenameField(
            model_name="turmaaluno",
            old_name="id_aluno",
            new_name="aluno",
        ),
        migrations.RenameField(
            model_name="turmaaluno",
            old_name="id_turma",
            new_name="turma",
        ),
        migrations.RenameField(
            model_name="turmadisciplina",
            old_name="id_disciplina",
            new_name="disciplina",
        ),
        migrations.RenameField(
            model_name="turmadisciplina",
            old_name="id_turma",
            new_name="turma",
        ),
        migrations.AlterUniqueTogether(
            name="turmaaluno",
            unique_together={("turma", "aluno")},
        ),
        migrations.AlterUniqueTogether(
            name="turmadisciplina",
            unique_together={("turma", "disciplina")},
        ),
        migrations.CreateModel(
            name="TurmaDisciplinaProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "INATIVO"), (1, "ATIVO")],
                        default=1,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "turma_disciplina",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.turmadisciplina",
                        verbose_name="Turma Disciplina",
                    ),
                ),
                (
                    "voluntario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.voluntario",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voluntário Disicplina",
                "verbose_name_plural": "Professores das Disciplinas nas Turmas",
                "unique_together": {("turma_disciplina", "voluntario")},
            },
        ),
    ]
