# Generated by Django 5.2.1 on 2025-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0015_rename_id_periodo_letivo_turma_periodo_letivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voluntario",
            name="disciplina",
            field=models.ManyToManyField(to="cadastros.disciplina"),
        ),
    ]
